version: "3.9"

services:
  web:
    build: .
    container_name: eventsoft_web
    env_file: 
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY:-changeme}
      DEBUG: ${DEBUG:-0}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
