# Generated by Django 5.2.1 on 2025-05-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nombre', models.CharField(max_length=100)),
                ('cat_descripcion', models.TextField(max_length=400)),
                ('cat_area_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_areas.areas')),
            ],
        ),
    ]
