# Generated by Django 5.2.7 on 2025-10-17 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdministradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_nombre', models.CharField(max_length=200)),
                ('eve_descripcion', models.TextField(blank=True)),
                ('eve_ciudad', models.CharField(max_length=100)),
                ('eve_lugar', models.CharField(max_length=100)),
                ('eve_fecha_inicio', models.DateField()),
                ('eve_fecha_fin', models.DateField()),
                ('eve_estado', models.CharField(max_length=20)),
                ('eve_capacidad', models.IntegerField()),
                ('eve_tienecosto', models.BooleanField(default=False)),
                ('eve_administrador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_super_admin.superadministradores')),
            ],
        ),
    ]
