# Generated by Django 5.2.7 on 2025-10-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_super_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventos',
        ),
    ]
