# Generated by Django 5.2.7 on 2025-10-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_asociado', models.EmailField(max_length=254, verbose_name='Email asociado')),
                ('codigo_hash', models.CharField(max_length=256, unique=True)),
                ('max_eventos', models.PositiveIntegerField(default=1)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de Acceso',
                'verbose_name_plural': 'Códigos de Acceso',
            },
        ),
        migrations.AlterModelOptions(
            name='superadministradores',
            options={'verbose_name': 'Super Administrador', 'verbose_name_plural': 'Super Administradores'},
        ),
    ]
