# Generated by Django 5.2.7 on 2025-10-17 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_super_admin', '0002_codigoacceso_alter_superadministradores_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodigoAcceso',
        ),
        migrations.AlterModelOptions(
            name='superadministradores',
            options={},
        ),
        migrations.AlterField(
            model_name='superadministradores',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
