# Generated by Django 5.2.3 on 2025-10-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_super_admin', '0002_delete_eventos'),
        ('app_super_admin', '0003_delete_codigoacceso_and_more'),
    ]

    operations = [
    ]
