# Generated by Django 5.2.1 on 2025-05-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_administrador', '0001_initial'),
        ('app_asistente', '0001_initial'),
        ('app_categorias', '0001_initial'),
        ('app_participante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_nombre', models.CharField(max_length=100)),
                ('eve_descripcion', models.TextField(max_length=400)),
                ('eve_ciudad', models.CharField(max_length=100)),
                ('eve_lugar', models.CharField(max_length=100)),
                ('eve_fecha_inicio', models.DateField()),
                ('eve_fecha_fin', models.DateField()),
                ('eve_estado', models.CharField(max_length=100)),
                ('eve_imagen', models.ImageField(upload_to='image/')),
                ('eve_capacidad', models.IntegerField()),
                ('eve_tienecosto', models.BooleanField(default=False)),
                ('eve_programacion', models.FileField(upload_to='pdf/programacion/')),
                ('eve_administrador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_administrador.administradores')),
            ],
        ),
        migrations.CreateModel(
            name='AsistentesEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_eve_fecha_hora', models.DateTimeField()),
                ('asi_eve_estado', models.CharField(max_length=45)),
                ('asi_eve_soporte', models.FileField(upload_to='pdf/comprobantes/')),
                ('asi_eve_qr', models.FileField(upload_to='pdf/qr_asistentes/')),
                ('asi_eve_clave', models.CharField(max_length=45)),
                ('asi_eve_asistente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_asistente.asistentes')),
                ('asi_eve_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.eventos')),
            ],
        ),
        migrations.CreateModel(
            name='EventosCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_cat_categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categorias.categorias')),
                ('eve_cat_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.eventos')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_eve_fecha_hora', models.DateTimeField()),
                ('par_eve_documentos', models.FileField(upload_to='pdf/proyectos/')),
                ('par_eve_estado', models.CharField(max_length=45)),
                ('par_eve_qr', models.FileField(upload_to='pdf/qr_participante/')),
                ('par_eve_clave', models.CharField(max_length=45)),
                ('par_eve_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.eventos')),
                ('par_eve_participante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_participante.participantes')),
            ],
        ),
    ]
