# Generated by Django 5.2.1 on 2025-05-31 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluador', '0001_initial'),
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteseventos',
            name='par_eve_calificacion_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EvaluadoresEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_eve_evaluador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluador.evaluadores')),
                ('eva_eve_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.eventos')),
            ],
        ),
    ]
