# Generated by Django 5.2.3 on 2025-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='eve_memorias',
            field=models.URLField(blank=True, null=True),
        ),
    ]
