# Generated by Django 5.2.1 on 2025-05-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_participanteseventos_par_eve_calificacion_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadoreseventos',
            name='eva_estado',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='evaluadoreseventos',
            name='eva_eve_fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluadoreseventos',
            name='eva_qr',
            field=models.FileField(blank=True, null=True, upload_to='pdf/qr_evaluador/'),
        ),
    ]
