# Generated by Django 5.2.3 on 2025-07-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_eventos_eve_memorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosInscripcionesEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitir_participantes', models.BooleanField(default=True)),
                ('permitir_evaluadores', models.BooleanField(default=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_inscripciones', to='app_eventos.eventos')),
            ],
        ),
    ]
