# Generated by Django 5.2.1 on 2025-05-31 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0003_evaluadoreseventos_eva_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluadoreseventos',
            old_name='eva_qr',
            new_name='eva_eve_qr',
        ),
    ]
