# Generated by Django 5.2.3 on 2025-07-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0003_estadosinscripcionesevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadoreseventos',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participanteseventos',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
