# Generated by Django 5.2.4 on 2025-07-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0004_evaluadoreseventos_habilitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='eve_habilitar_evaluadores',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='eve_habilitar_participantes',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='EstadosInscripcionesEvento',
        ),
    ]
