# Generated by Django 5.2.3 on 2025-06-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0004_rename_eva_qr_evaluadoreseventos_eva_eve_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='eve_informacion_tecnica',
            field=models.FileField(blank=True, null=True, upload_to='pdf/info_tecnica/'),
        ),
    ]
