# Generated by Django 5.2.3 on 2025-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0005_eventos_eve_informacion_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadoreseventos',
            name='eva_clave_acceso',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
