# Generated by Django 5.2.3 on 2025-09-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0005_eventos_eve_habilitar_evaluadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='eve_programacion',
            field=models.FileField(blank=True, null=True, upload_to='pdf/programacion/'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_codigo', models.CharField(max_length=8)),
                ('pro_nombre', models.CharField(max_length=100)),
                ('pro_descripcion', models.TextField(max_length=400)),
                ('pro_documentos', models.FileField(upload_to='pdf/proyectos/')),
                ('pro_fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('pro_estado', models.CharField(max_length=45)),
                ('pro_calificación_final', models.FloatField(blank=True, null=True)),
                ('pro_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.eventos')),
            ],
        ),
        migrations.AddField(
            model_name='participanteseventos',
            name='par_eve_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_eventos.proyecto'),
        ),
    ]
