# Generated by Django 5.2.3 on 2025-06-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0006_evaluadoreseventos_eva_clave_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadoreseventos',
            name='eva_eve_documentos',
            field=models.FileField(blank=True, null=True, upload_to='pdf/soporte_evaluador/'),
        ),
    ]
