# Generated by Django 5.2.3 on 2025-09-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0006_alter_eventos_eve_programacion_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadoreseventos',
            name='eva_eve_areas_interes',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
