# Generated by Django 5.2.7 on 2025-10-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0007_evaluadoreseventos_eva_eve_areas_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenteseventos',
            name='asi_eve_fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
