# Generated by Django 5.2.3 on 2025-11-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0008_alter_asistenteseventos_asi_eve_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadoreseventos',
            name='criterios_modificables',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
