# Generated by Django 5.2.3 on 2025-12-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0009_evaluadoreseventos_criterios_modificables'),
    ]

    operations = [
    ]
