# Generated by Django 5.2.3 on 2026-03-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0009_evaluadoreseventos_criterios_modificables'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenteseventos',
            name='asistencia_confirmada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='evaluadoreseventos',
            name='asistencia_confirmada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='participanteseventos',
            name='asistencia_confirmada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
