# Generated by Django 5.2.3 on 2025-12-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0010_agregar_criterios_modificables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='eve_capacidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
