# Generated by Django 5.2.3 on 2026-03-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0010_asistenteseventos_asistencia_confirmada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenteseventos',
            name='asi_eve_qr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistenteseventos',
            name='asi_eve_soporte',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluadoreseventos',
            name='eva_eve_documentos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluadoreseventos',
            name='eva_eve_qr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='eve_imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='eve_informacion_tecnica',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='eve_programacion',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participanteseventos',
            name='par_eve_documentos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participanteseventos',
            name='par_eve_qr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='pro_documentos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
