# Generated by Django 5.2.1 on 2025-05-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_cedula', models.CharField(max_length=10)),
                ('adm_nombre', models.CharField(max_length=100)),
                ('adm_correo', models.EmailField(max_length=100)),
                ('adm_telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
