# Generated by Django 5.2.3 on 2025-07-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='num_eventos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='tiempo_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
