# Generated by Django 5.2.1 on 2025-05-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0002_asistenteseventos_participanteseventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri_descripcion', models.CharField(max_length=100)),
                ('cri_peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cri_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criterios', to='app_eventos.eventos')),
            ],
        ),
    ]
