# Generated by Django 5.2.3 on 2025-06-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_criterios', '0001_initial'),
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterios',
            name='cri_evento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criterios', to='app_eventos.eventos'),
        ),
    ]
