# Generated by Django 5.2.3 on 2026-04-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_criterios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterios',
            name='cri_descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
