# Generated by Django 5.2.3 on 2025-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('are_nombre', models.CharField(max_length=100)),
                ('are_descripcion', models.TextField(max_length=400)),
            ],
        ),
    ]
