# Generated by Django 5.2.3 on 2025-07-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0002_eventos_eve_memorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseño', models.ImageField(blank=True, null=True, upload_to='pdf/certificados/diseños/')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='pdf/certificados/firma/')),
                ('firma_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('orientacion', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=10)),
                ('evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='app_eventos.eventos')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
