# Generated by Django 5.2.3 on 2025-07-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certifica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='lugar_expedicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='tipografia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
