# Generated by Django 5.2.3 on 2026-03-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificados', '0002_certificado_certifica_certificado_lugar_expedicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='diseño',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='firma',
            field=models.URLField(blank=True, null=True),
        ),
    ]
