# Generated by Django 5.2.1 on 2025-05-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asistente', '0002_alter_asistentes_asi_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='asistentes',
            old_name='asi_nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='asistentes',
            name='asi_cedula',
        ),
        migrations.RemoveField(
            model_name='asistentes',
            name='asi_correo',
        ),
        migrations.RemoveField(
            model_name='asistentes',
            name='asi_telefono',
        ),
        migrations.AddField(
            model_name='asistentes',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asistentes',
            name='telefono',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='asistentes',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AsistenteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('soporte', models.BinaryField(blank=True, null=True)),
                ('qr', models.BinaryField(blank=True, null=True)),
                ('clave', models.CharField(blank=True, max_length=45, null=True)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_asistente.asistentes')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_asistente.evento')),
            ],
            options={
                'unique_together': {('asistente', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='asistentes',
            name='eventos',
            field=models.ManyToManyField(related_name='asistentes', through='app_asistente.AsistenteEvento', to='app_asistente.evento'),
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_asistente.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_asistente.evento')),
            ],
            options={
                'unique_together': {('evento', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(related_name='eventos', through='app_asistente.EventoCategoria', to='app_asistente.categoria'),
        ),
    ]
