# Generated by Django 5.2.3 on 2025-06-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
