# Generated by Django 5.2.3 on 2025-06-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_usuario_segundo_apellido_usuario_segundo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.DateField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
