# Generated by Django 5.2.3 on 2025-06-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido'),
        ),
    ]
