# Generated by Django 5.2.1 on 2025-05-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_cedula', models.CharField(max_length=10, unique=True)),
                ('par_nombre', models.CharField(max_length=100)),
                ('par_correo', models.EmailField(max_length=100)),
                ('par_telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
