# Generated by Django 5.2.1 on 2025-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='par_cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
