# Generated by Django 5.2.1 on 2025-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participante', '0002_alter_participantes_par_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
