# Generated by Django 5.2.1 on 2025-05-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_criterios', '0001_initial'),
        ('app_participante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_cedula', models.CharField(max_length=10, unique=True)),
                ('eva_nombre', models.CharField(max_length=100)),
                ('eva_correo', models.EmailField(max_length=100)),
                ('eva_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cal_criterio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterio_calificaciones', to='app_criterios.criterios')),
                ('clas_participante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_calificaciones', to='app_participante.participantes')),
                ('cal_evaluador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluador_calificaciones', to='app_evaluador.evaluadores')),
            ],
        ),
    ]
