# Generated by Django 5.2.3 on 2025-06-17 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_criterios', '0001_initial'),
        ('app_participante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cal_comentario', models.TextField(blank=True, null=True)),
                ('cal_criterio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterio_calificaciones', to='app_criterios.criterios')),
                ('clas_participante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_calificaciones', to='app_participante.participantes')),
                ('cal_evaluador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluador_calificaciones', to='app_evaluador.evaluadores')),
            ],
        ),
    ]
