# Generated by Django 5.2.1 on 2025-06-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='cal_comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
