# Generated by Django 5.2.3 on 2025-09-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluador', '0001_initial'),
        ('app_eventos', '0007_evaluadoreseventos_eva_eve_areas_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluadorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_pro_evaluador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluador', to='app_evaluador.evaluadores')),
                ('eva_pro_proyecto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='app_eventos.proyecto')),
            ],
        ),
    ]
