# Generated by Django 5.2.3 on 2025-06-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluador', '0002_calificaciones_cal_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadores',
            name='eva_documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos_evaluadores/'),
        ),
    ]
