# Generated by Django 5.2.3 on 2025-09-11 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluador', '0002_evaluadorproyecto'),
        ('app_eventos', '0007_evaluadoreseventos_eva_eve_areas_interes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='clas_participante_fk',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='clas_proyecto_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_calificaciones', to='app_eventos.proyecto'),
        ),
    ]
