# Generated by Django 5.2.3 on 2025-06-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluador', '0003_evaluadores_eva_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluadores',
            name='eva_documento',
        ),
    ]
